CREATE TABLE IF NOT EXISTS window_state (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  x INTEGER NOT NULL DEFAULT 0,
  y INTEGER NOT NULL DEFAULT 0,
  width INTEGER NOT NULL DEFAULT 1400,
  height INTEGER NOT NULL DEFAULT 900,
  is_maximized INTEGER NOT NULL DEFAULT 0,
  updated_at INTEGER NOT NULL DEFAULT (unixepoch())
);
